version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 4200:4200 
  backend:
    build:
      context: ./backend 
      dockerfile: Dockerfile.backend 
    ports:
      - 3000:3000 
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=${MONGO_URL}
  mongodb:
    image: mongo
    ports:
      - 27017:27017 
    volumes:
      - ./data:/data/db